FROM ruby:3.3-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential libsqlite3-dev sqlite3 libvips42 libheif1 exiftool ffmpeg \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

CMD ["bin/rails", "runner", "puts Rails.version"]
