#!/usr/bin/env bash
# Local Kamal deploy loop for macOS. Exercises the full Kamal orchestration
# against this machine: SSH-to-localhost, throwaway registry on :5555,
# kamal-proxy on :80, the Rails app, and the sidecar accessory.
#
#   script/kamal-local.sh preflight  # check ssh / ports / RAILS_MASTER_KEY
#   script/kamal-local.sh up         # registry -> build/push -> deploy -> accessory -> smoke
#   script/kamal-local.sh smoke      # re-run the smoke check against a running stack
#   script/kamal-local.sh status     # show the stack
#   script/kamal-local.sh down       # remove app, accessory, proxy, registry, volumes
set -euo pipefail

SERVICE="photo_searchable_library_rails"
REGISTRY_IP="${KAMAL_LOCAL_REGISTRY_IP:-$(ipconfig getifaddr en0 2>/dev/null || true)}"
REGISTRY_HOST="${REGISTRY_IP}:5555"
REGISTRY_CONTAINER="kamal-local-registry"
REGISTRY_USER="kamal-local"
REGISTRY_PASSWORD="${KAMAL_LOCAL_REGISTRY_PASSWORD:-$(openssl rand -hex 24)}"
REGISTRY_AUTH_FILE="/tmp/kamal-local-registry.htpasswd"
APP_IMAGE="$REGISTRY_HOST/$SERVICE"
LOCAL_CONFIG="config/deploy.local.yml"
DOCKER_CREDENTIALS_FILE="${HOME}/.docker/kamal-local/credentials"

info() { printf '\n==> %s\n' "$*"; }
die()  { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

require_env() {
  if [ -z "${RAILS_MASTER_KEY:-}" ]; then
    die "RAILS_MASTER_KEY is not set. Export it from your password manager, then re-run."
  fi
}

preflight() {
  require_env
  [ -n "$REGISTRY_IP" ] || die "Cannot determine the local LAN IP. Set KAMAL_LOCAL_REGISTRY_IP before running."

  if ! docker info --format '{{json .RegistryConfig.IndexConfigs}}' \
    | python3 -c 'import json, sys; configs = json.load(sys.stdin); host = sys.argv[1]; sys.exit(0 if configs.get(host, {}).get("Secure") is False else 1)' "$REGISTRY_HOST"; then
    die "Docker does not trust the plain-HTTP registry $REGISTRY_HOST. Add $REGISTRY_HOST to Docker Desktop Settings > Docker Engine > insecure-registries, then Apply & Restart."
  fi

  info "SSH to localhost"
  ssh -o BatchMode=yes -o ConnectTimeout=5 localhost true 2>/dev/null \
    || die "Cannot SSH to localhost. Enable Remote Login and authorize your key: ssh-copy-id localhost"

  info "Port 80 (kamal-proxy)"
  if lsof -nP -iTCP:80 -sTCP:LISTEN >/dev/null 2>&1; then
    die "Port 80 is already in use; stop the other service first (it would collide with kamal-proxy)."
  fi

  info "Port 5555 (throwaway registry)"
  if lsof -nP -iTCP:5555 -sTCP:LISTEN >/dev/null 2>&1; then
    die "Port 5555 is already in use; stop the other service first."
  fi

  info "Port 9090 (sidecar accessory)"
  if lsof -nP -iTCP:9090 -sTCP:LISTEN >/dev/null 2>&1; then
    die "Port 9090 is already in use. The dev stack (bin/dev-docker) must not run alongside this loop."
  fi

  command -v docker >/dev/null || die "docker is required"
  info "Preflight OK"
}

write_config() {
  local version
  version=$(git rev-parse HEAD)

  cat > "$LOCAL_CONFIG" <<YAML
# Generated by script/kamal-local.sh - machine-specific, do not commit.
# Merges over config/deploy.yml for every bin/kamal ... -d local invocation.
servers:
  web:
    - localhost

registry:
  server: ${REGISTRY_HOST}
  username: ${REGISTRY_USER}
  password: ${REGISTRY_PASSWORD}

ssh:
  user: ${USER}
  port: 22

accessories:
  sidecar:
    image: ${SERVICE}_sidecar:${version}
    host: localhost
    port: "9090:9090"
    registry:
      server: ${REGISTRY_HOST}
      username: ${REGISTRY_USER}
      password: ${REGISTRY_PASSWORD}
YAML
}

ensure_registry() {
  mkdir -p "$(dirname "$DOCKER_CREDENTIALS_FILE")"
  printf '%s\n' "$REGISTRY_PASSWORD" > "$DOCKER_CREDENTIALS_FILE"
  chmod 600 "$DOCKER_CREDENTIALS_FILE"

  if ! docker inspect "$REGISTRY_CONTAINER" >/dev/null 2>&1; then
    info "Creating throwaway registry credentials"
    docker run --rm httpd:2-alpine htpasswd -Bbn "$REGISTRY_USER" "$REGISTRY_PASSWORD" > "$REGISTRY_AUTH_FILE"
    info "Starting throwaway registry on $REGISTRY_HOST"
    docker run -d --name "$REGISTRY_CONTAINER" --restart=no \
      -p "${REGISTRY_IP}:5555:5000" \
      -e REGISTRY_AUTH=htpasswd \
      -e REGISTRY_AUTH_HTPASSWD_REALM="Local Registry" \
      -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
      -v "$REGISTRY_AUTH_FILE:/auth/htpasswd:ro" \
      registry:2
  else
    info "Registry container already present"
  fi

  info "Waiting for registry /v2/"
  for i in $(seq 1 30); do
    if curl -fsS -u "$REGISTRY_USER:$REGISTRY_PASSWORD" "http://$REGISTRY_HOST/v2/" >/dev/null 2>&1; then
      echo "    ready after ${i}s"
      return 0
    fi
    sleep 1
  done
  die "Registry at $REGISTRY_HOST never came up; check: docker logs $REGISTRY_CONTAINER"
}

push_sidecar() {
  info "Logging into throwaway registry"
  printf '%s\n' "$REGISTRY_PASSWORD" | docker login "$REGISTRY_HOST" --username "$REGISTRY_USER" --password-stdin
  local version
  version=$(git rev-parse HEAD)
  local sidecar_image="$REGISTRY_HOST/${SERVICE}_sidecar:$version"
  info "Building sidecar image (amd64 emulation; pulls torch, allow several minutes)"
  docker build --platform linux/amd64 -f sidecar/Dockerfile -t "$sidecar_image" .
  info "Pushing sidecar image to $REGISTRY_HOST"
  docker push "$sidecar_image"
}

deploy_app() {
  local version
  version=$(git rev-parse HEAD)
  info "Building Rails image with the host Docker client"
  docker build --platform linux/amd64 \
    --label "service=$SERVICE" \
    -t "$APP_IMAGE:$version" .
  info "Pushing Rails image to $REGISTRY_HOST"
  docker push "$APP_IMAGE:$version"
  info "bin/kamal deploy -P -d local (pulls app image, boots proxy + app)"
  bin/kamal deploy -P -d local
  info "Booting sidecar accessory"
  bin/kamal accessory boot sidecar -d local
}

wait_up() {
  info "Waiting for app /up through the proxy on :80"
  for i in $(seq 1 90); do
    if curl -fsS "http://localhost/up" >/dev/null 2>&1; then
      echo "    up after ${i}s"
      return 0
    fi
    sleep 1
  done
  die "App never answered /up. Check: bin/kamal app logs -d local"
}

wait_sidecar() {
  info "Waiting for sidecar /v1/status (models loaded) on :9090"
  for i in $(seq 1 300); do
    if curl -fsS "http://localhost:9090/v1/status" 2>/dev/null \
      | python3 -c "import json,sys; sys.exit(0 if json.load(sys.stdin).get('ok') else 1)" 2>/dev/null; then
      echo "    ready after ${i}s"
      return 0
    fi
    sleep 2
  done
  die "Sidecar never reported ready. Check: bin/kamal accessory logs sidecar -d local"
}

smoke() {
  wait_up
  wait_sidecar

  info "Smoke: catalog overview"
  curl -fsS -H "Accept: application/json" "http://localhost/catalog/overview" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); print('    sources:', [s['kind'] for s in d['sources']])"

  info "Smoke: upload test/fixtures/tiny.jpg"
  RESP=$(curl -fsS -H "Accept: application/json" \
    -F "file=@test/fixtures/tiny.jpg;type=image/jpeg" "http://localhost/assets/upload")
  JOB_ID=$(printf '%s' "$RESP" | python3 -c "import json,sys; print(json.load(sys.stdin)['job_id'])")
  echo "    job_id=$JOB_ID"

  info "Smoke: wait for import job (first run may download weights)"
  for i in $(seq 1 180); do
    STATUS=$(curl -fsS "http://localhost/jobs/$JOB_ID" \
      | python3 -c "import json,sys; print(json.load(sys.stdin)['status'])")
    if [ "$STATUS" = "done" ]; then
      echo "    done after ${i}s"
      break
    fi
    if [ "$STATUS" = "error" ]; then
      die "Import job errored. Check: bin/kamal app logs -d local"
    fi
    if [ "$i" = 180 ]; then
      die "Import job timed out. Check: bin/kamal app logs -d local"
    fi
    sleep 1
  done

  info "Smoke: thumbnail serves"
  ASSET_ID=$(curl -fsS -H "Accept: application/json" "http://localhost/catalog/overview" \
    | python3 -c "import json,sys; d=json.load(sys.stdin); print(d['context']['recent_imports'][0]['id'])")
  curl -fsS -o /tmp/kamal-local-thumb.jpg -w "    thumbnail HTTP %{http_code}\n" \
    "http://localhost/assets/$ASSET_ID/thumbnail"
  info "SMOKE OK"
}

status() {
  info "Kamal details"
  bin/kamal details -d local 2>&1 | head -40 || true
  info "Containers"
  docker ps --filter "name=photo_searchable_library_rails" \
    --filter "name=kamal-proxy" \
    --filter "name=kamal-local-registry" \
    --format "table {{.Names}}\t{{.Image}}\t{{.Ports}}" || true
  info "Volumes"
  docker volume ls | grep photo_searchable_library_rails || true
}

down() {
  info "Removing app, proxy, and accessories"
  bin/kamal remove -d local -y 2>&1 || true
  if docker inspect "$REGISTRY_CONTAINER" >/dev/null 2>&1; then
    info "Removing throwaway registry"
    docker rm -f "$REGISTRY_CONTAINER"
  fi
  rm -f "$REGISTRY_AUTH_FILE"
  rm -f "$DOCKER_CREDENTIALS_FILE"
  docker volume rm "${SERVICE}_models" >/dev/null 2>&1 || true
  info "DOWN OK"
}

cmd="${1:-help}"
case "$cmd" in
  preflight)  preflight ;;
  up)         preflight; write_config; ensure_registry; push_sidecar; deploy_app; smoke ;;
  smoke)      smoke ;;
  status)     status ;;
  down)       down ;;
  help|-h|--help) sed -n '2,10p' "$0" ;;
  *) die "unknown subcommand '$cmd' (use: preflight | up | smoke | status | down)" ;;
esac
